config/routes.rb
Rails.application.routes.draw do

  get 'formation/retour' => 'formation#destroy', :as => "enleve"

  get 'mes_cours/litterature'

  get 'mes_cours/methode'

  get 'mes_cours/grammaire'

  get 'mes_cours/stylistique'

  resources :userlitts

  get 'log_out' => 'sessions#destroy', :as => "log_out"

  get 'log_in' => 'sessions#new', :as => "log_in"

  get 'sign_up' => 'users#new', :as => 'sign_up'
  
  get 'formation/module'

  get 'bibliotheque/construction'

  get 'bibliotheque/parniveau'

  get 'bibliotheque/parsiecle'

  get 'bibliotheque/parauteur'

  get 'bibliotheque/methode'

  get 'bibliotheque/grammaire'

  get 'bibliotheque/stylistique'

  get 'bibliotheque/nouveautes'

  get 'accueil/connexion'

  get 'accueil/inscription'

  get 'accueil/visite'
  
  get 'accueil/bio'

  resources :mouvements
  resources :genres
  resources :lienthemes
  resources :themes
  resources :passages
  resources :auteurs
  resources :oeuvres
  resources :users
  resources :sessions

  get 'accueil/index'
  root :to => 'accueil#index'

end

app/controllers/bibliotheque_controller.rb
class BibliothequeController < ApplicationController

  def parniveau
  	@oeuvres = Oeuvre.all
  	@passages = Passage.all
  	@themes = Theme.all.order(:niveau)
  	@lienthemes = Lientheme.all
  	@niveau = Theme.all
  end

  def parsiecle
  	@oeuvres = Oeuvre.all.order(:date)
  end

  def parauteur
    @auteurs = Auteur.all.order(:nom_entier)
      if params['auteur'] != nil
      @auteur = Auteur.where(nom_entier: params['auteur'])
      @oeuvres = Oeuvre.where(auteur_id: @auteur)
      else
      @oeuvres = Oeuvre.all.order(:date)
      end
    @lienthemes = Lientheme.all
  end

  def methode
  end

  def nouveautes
    @oeuvres = Oeuvre.limit(5).order('updated_at desc')
  end

end

app/controllers/formation_controller.rb
class FormationController < ApplicationController
  def module
  	@oeuvres = Oeuvre.includes(:auteur).all
  	@oeuvre = Oeuvre.find(params[:formation])
  	@auteur = Auteur.find(@oeuvre.auteur_id)
  	@passages = Passage.all
  		if params['module'] != nil
  		@passage = Passage.find(params['module'])
  		end
  	@auteurs = Auteur.all
  	@lienthemes = Lientheme.where(oeuvre:params['formation'])
    @userlitt = Userlitt.where(user_id:current_user).where(oeuvre_id:params["formation"])
  end

  def destroy
    @userlitt.destroy
    respond_to do |format|
      format.html { redirect_to mes_cours_litt, notice: "Ce cours n'est plus dans votre espace" }
      format.json { head :no_content }
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, only: [:show, :edit, :update, :destroy, :index]


  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Bienvenue sur votre nouveau compte !"
    else
      render "new"
    end
  end
  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'Le compte est mis a jour.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Le compte est supprime.' }
      format.json { head :no_content }
    end
  end

private

  def user_params
    params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password)
  end

  def set_user
      @user = User.find(params[:id])
  end

end

app/views/accueil/bio.html.erb
<video poster="poster.png" controls width="1024px" height="640px" autoplay preload="metadata">
  <source src="https://s3-eu-west-1.amazonaws.com/acquis/technique/methode1.mp4"></source>
</video>

app/views/accueil/index.html.erb
<%= link_to('bibliotheque/parsiecle') do %><%= image_tag 'promo1.jpg', :class => 'imagepromo' %><% end %>
<div class = "promo">Commentaires composés pour le collège et le lycée. </div><br>

<%= link_to('bibliotheque/parsiecle') do %><%= image_tag 'promo2.jpg', :class => 'imagepromo' %><% end %>
<div class = "promo">Les meilleures méthodes pédagogiques en vidéo.</div><br>

<%= link_to('bibliotheque/parsiecle') do %><%= image_tag 'promo4.jpg', :class => 'imagepromo' %><% end %>
<div class = "promo">Visionnez n'importe quel cours à volonté.</div><br>

app/views/accueil/visite.html.erb
<br><h1>Désolé...</h1>

Le contenu est encore en construction !

app/views/bibliotheque/construction.html.erb
<div class = "entree">
<%= render 'entree' %>
<br>

<div class = "sortie">
<%= render 'sortie' %>
</div>

<div class = "bibli">
		<ul>
			<li>
			<%= link_to 'Situer un texte', bibliotheque_methode_path %>
			</li>
			<li>
			<%= link_to 'Analyser un texte', bibliotheque_methode_path %>
			</li>
			<li>
			<%= link_to "Méthodologie", bibliotheque_methode_path %>
			</li>
			<li>
			<%= link_to "Conjugaison", bibliotheque_methode_path %>
			</li>
			<li>
			<%= link_to "Grammaire", bibliotheque_methode_path %>
			</li>
			<li>
			<%= link_to "Orthographe", bibliotheque_methode_path %>
			</li>
		</ul>
</div>
</div>

app/views/bibliotheque/methode.html.erb
<div class = "entree">
<%= render 'entree' %>
<br>

<div class = "sortie">
<%= render 'sortie' %>
</div>

<div class = "bibli">
		<ul>
			<li>
			<%= link_to 'Situer un texte', accueil_visite_path %>
			</li>
			<li>
			<%= link_to 'Analyser un texte', accueil_visite_path %>
			</li>
			<li>
			<%= link_to "Méthodologie", accueil_visite_path %>
			</li>
			<li>
			<%= link_to "Conjugaison", accueil_visite_path %>
			</li>
			<li>
			<%= link_to "Grammaire", accueil_visite_path %>
			</li>
			<li>
			<%= link_to "Orthographe", accueil_visite_path %>
			</li>
		</ul>
</div>
</div>

app/views/bibliotheque/parsiecle.html.erb
<div class = "entree">
<%= render 'entree' %>
<br>

<div class = "sortie">
<%= render 'sortie' %>
</div>

<div>
		<ul>
		<% if params['filtre'] == "16e" %><li class = "li_2"><% end %>
		<%= link_to 'XVIe siècle', bibliotheque_parsiecle_path(:filtre => '16e') %></li><br>
		<% if params['filtre'] == "17e" %><li class = "li_2"><% end %>
		<%= link_to 'XVIIe siècle', bibliotheque_parsiecle_path(:filtre => '17e') %></li><br>
		<% if params['filtre'] == "18e" %><li class = "li_2"><% end %>
		<%= link_to 'XVIIIe siècle', bibliotheque_parsiecle_path(:filtre => '18e') %></li><br>
		<% if params['filtre'] == "19e" %><li class = "li_2"><% end %>
		<%= link_to 'XIXe siècle', bibliotheque_parsiecle_path(:filtre => '19e') %></li><br>
		<% if params['filtre'] == "20e" %><li class = "li_2"><% end %>
		<%= link_to 'XXe siècle', bibliotheque_parsiecle_path(:filtre => '20e') %></li><br>
		</ul>
</div>
</div>

app/views/formation/module.html.erb
<br>
<h1>
<%= @auteur.nom_entier+', '+@oeuvre.titre_oeuvre+' ('+@oeuvre.date.to_s+')' %>
</h1>
<br>
<% if params['module'] == nil %>
<h2>Emplacement dans la bibliothèque :</h2>
<ul>
	<li>Par niveau
		<ul>
   			<% @lienthemes.each do |t| %>
       		<li><%= 'Étudié en '+t.theme.niveau+' dans la thématique  "'+t.theme.titre_theme+'"' %></li>
    		<% end %>
    	</ul>
    </li>
	<li>Par siècle : 
		<ul><li>
		<% case @oeuvre.date %>
			<% when '< 0' %>
			Antiquité
			<% when 0..1500 %>
			Moyen-âge
			<% when 1501..1600 %>
			XVIe siècle
			<% when 1601..1700 %>
			XVIIe siècle
			<% when 1701..1800 %>
			XVIIIe siècle
			<% when 1801..1900 %>
			XIXe siècle
			<% when 1901..2000 %>
			XXe siècle
			<% when 2001..2100 %>
			XXIe siècle
	<% end %>
	<%= '(Oeuvre publiée en '+@oeuvre.date.to_s+')' %></li>
	</ul></li>
	<li>
	Par auteur : 
	<ul><li>
		<%= @auteur.prenom+' '+@auteur.nom+' simplement appelé '+@auteur.nom_entier+', né en '+@auteur.date_n.to_s+' et mort en '+@auteur.date_m.to_s %></li>
</ul></ul>
<% end %>

<% if params['module'] != nil %>
<script type="text/javascript" src="http://www.supportduweb.com/page/js/flashobject.js"></script>
<div id="player_2532" style="display:inline-block;">
    <a href="http://get.adobe.com/flashplayer/">Essayez de recharger la page, si cela ne fonctionne toujours pas, cliquez sur ce lien pour installer le plugin Flash</a> - <a href="http://www.supportduweb.com/">http://www.supportduweb.com/</a>
</div>
<script type="text/javascript">
    var flashvars_2532 = {};
    var params_2532 = {
        quality: "high",
        wmode: "transparent",
        bgcolor: "#ffffff",
        allowScriptAccess: "always",
        allowFullScreen: "true",
        flashvars: "fichier=https://s3-eu-west-1.amazonaws.com/acquis/litterature/<%= @passage.video %>&apercu=poster.png"
    };
    var attributes_2532 = {};
    flashObject("http://flash.supportduweb.com/flv_player/v1_13.swf", "player_2532", "1024", "640", "8", false, flashvars_2532, params_2532, attributes_2532);
</script>
<% end %>

app/views/layouts/_matieres.html.erb
<div class = "aside">

<% case params['controller'] %>
<% when 'bibliotheque' %>

	<% if params['action'] == 'nouveautes' %><strong><% end %>
	<%= link_to "Nouveautés", bibliotheque_nouveautes_path %></strong><br><br>

	<h3>Français </h3>

	<% if params['action'] == 'parauteur' or params['action'] == 'parsiecle' or params['action'] == 'parniveau' %><strong><% end %>
	<%= link_to "Commentaires composés", bibliotheque_parauteur_path %></strong><br><br>

	<% if params['action'] == 'methode' %><strong><% end %>
	<%= link_to "Méthodes et techniques", bibliotheque_methode_path %></strong><br><br>

<% when 'mes_cours' %>

	<% if params['action'] == 'nouveautes' %><strong><% end %>
	<%= link_to "Nouveautés", bibliotheque_nouveautes_path %></strong><br><br>

	<h3>Français </h3>

	<% if params['action'] == 'litterature' %><strong><% end %>
	<%= link_to "Littérature", mes_cours_litterature_path %></strong><br><br>

	<% if params['action'] == 'methode' %><strong><% end %>
	<%= link_to "Méthodes et techniques", bibliotheque_methode_path %></strong><br><br>

<% when 'accueil' %>

	<% if params['action'] == 'bio' %>
	<%= link_to "Compte gratuit !", '../users/new' %><br><br>
	<strong><%= link_to "Voir la méthodologie", 'bio' %></strong><br><br>

	<% else %>
	<%= link_to "Compte gratuit !", 'users/new' %><br><br>
	<%= link_to "Voir la méthodologie", 'accueil/bio' %><br><br>
	<% end %>

<% when 'users' %>

	<strong><%= link_to "Compte gratuit !", 'users/new' %></strong><br><br>
	<%= link_to "Voir la méthodologie", '../accueil/bio' %><br><br>

<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mediaclasse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<script language="JavaScript1.2">
function nosource()
{
;
return(false);
}
document.oncontextmenu = nosource;
</script>

<header>
	<% if params['controller'] == 'accueil' %>
	<div id = "logo"><a href="/"><%= image_tag 'logo_on.png', :size => "60x60" %></a></div>
	<% else %>
	<div id = "logo"><a href="/"><%= image_tag 'logo_off.png', :size => "60x60" %></a></div>
	<% end %>
<%= render 'layouts/nav' %>
</header>

<% case params['controller'] %>
<% when 'accueil' %>
	<aside><%= render 'layouts/matieres' %></aside>
	<%= render 'layouts/connexion' %>
	<body class = "visite">
<% when 'users' %>
	<aside><%= render 'layouts/matieres' %></aside>
	<body class = "visite">
<% when 'sessions' %>
	<aside><%= render 'layouts/matieres' %></aside>
	<body class = "visite">
<% when "bibliotheque" %>
	<aside><%= render 'layouts/matieres' %></aside>
	<%= render 'layouts/connexion' %>
	<body class = "visite">
<% when "mes_cours" %>
	<aside><%= render 'layouts/matieres' %></aside>
	<%= render 'layouts/connexion' %>
	<body class = "visite">
<% when "formation" %>
	<aside><%= render 'layouts/chapitres' %></aside>
	<%= render 'layouts/connexion' %>
	<body class = "visite">
<% else %>
	<body class = "admin">
<% end %>

<div class = "notice">
	<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>
</div>

<%= yield %>

</body>
</html>